name: "Book Tracker: Close Issue"
on:
  issues:
    types: [closed]
jobs:
  book-tracker:
    name: Book Tracker
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Run Book Tracker
        uses: AnandChowdhary/book-tracker@HEAD
        with:
          command: "onCloseIssue"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
