name: Build CI

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build and publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Build package
        run: npm run package

      - name: Publish package
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: ":rocket: Deploy new version [skip ci]"
          commit_user_name: Finding Anand
          commit_user_email: bot@anandchowdhary.com
          commit_author: Finding Anand <bot@anandchowdhary.com>
